### ISSUE TITLE
Interactive figures for flash flood story

### ISSUE THREAD

**Issue by SarahAlidoost** [eucp-project/storyboards#32]
Two figures in the "Alpine flash floods" (see PR #31) can be interactive. For more info, see comments in the raw ppt material, slides numbers 7 & 9.

**Comment by Peter9192** [comment]
If I understand correctly, these are standalone HTML files produced with mapbox. The easiest way might be to embed them using an iframe. So in the `_panel.vue` we could check if the image extension is HTML, and in that case create an iframe instead of an image tag.

The index page now only uses the first image, but we might want to make sure that this page won't fail if we also allow html as main content.

**Comment by geek-yang** [comment]
It is done.
